---

services:

  goapp:
    container_name: app
    build:
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./.env-linux

# networks:
#   db:
#     driver: bridge

# --- EOF
