// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
package ui

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

// Styles etc for Bootstrap

var BootstrapCSS = "https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"

var red = "#ff0000"
var blue = "#0000ff"

func primaryClassName() templ.CSSClass {
	templ_7745c5c3_CSSBuilder := templruntime.GetBuilder()
	templ_7745c5c3_CSSBuilder.WriteString(`background-color:#ffffff;`)
	templ_7745c5c3_CSSBuilder.WriteString(string(templ.SanitizeCSS(`color`, red)))
	templ_7745c5c3_CSSID := templ.CSSID(`primaryClassName`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func body() templ.CSSClass {
	templ_7745c5c3_CSSBuilder := templruntime.GetBuilder()
	templ_7745c5c3_CSSBuilder.WriteString(`background-color:#f0f0f0;`)
	templ_7745c5c3_CSSBuilder.WriteString(`min-height:75rem;`)
	templ_7745c5c3_CSSBuilder.WriteString(`padding-top:4.5rem;`)
	templ_7745c5c3_CSSID := templ.CSSID(`body`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func Style() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<style>\n\t\tbody {\n\t\t\tbackground-color: rgb(217, 224, 225);\n\t\t\tmin-height: 75rem;\n\t\t\tpadding-top: 4.5rem; }\n\t\th1 {\n\t\t\tcolor: { blue } ; }\n\t\tp {\n\t\t\tcolor: red; }\n\t\t.pagination {\n\t\t\tfloat: left;\n\t\t\tmargin: 0 0 5px; }\n\t\t.pagination li a {\n\t\t\tborder: none;\n\t\t\t// font-size: 13px;\n\t\t\tmin-width: 30px;\n\t\t\tmin-height: 30px;\n\t\t\tcolor: #999;\n\t\t\tmargin: 0 2px;\n\t\t\tline-height: 30px;\n\t\t\tborder-radius: 2px !important;\n\t\t\ttext-align: center;\n\t\t\tpadding: 0 6px; }\n\t\t.pagination li a:hover {\n\t\t\t\t\tcolor: #666;\n\t\t\t\t}\n\t\t\t\n\t\t\t\t.pagination li.active a,\n\t\t\t\t.pagination li.active a.page-link {\n\t\t\t\t\tbackground: #03A9F4;\n\t\t\t\t}\n\t\t\t\n\t\t\t\t.pagination li.active a:hover {\n\t\t\t\t\tbackground: #0397d6;\n\t\t\t\t}\n\t\t\t\n\t\t\t\t.pagination li.disabled i {\n\t\t\t\t\tcolor: #ccc;\n\t\t\t\t}\n\t\t\t\n\t\t\t\t.pagination li i {\n\t\t\t\t\tfont-size: 16px;\n\t\t\t\t\tpadding-top: 6px\n\t\t\t\t}\n\t\t\t\n\t\t\t\t.hint-text {\n\t\t\t\t\tfloat: left;\n\t\t\t\t\tmargin-top: 10px;\n\t\t\t\t\t// font-size: 13px;\n\t\t\t\t}\n\t\t\t</style>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

// --- EOF
var _ = templruntime.GeneratedTemplate
